// <auto-generated />
namespace Uni_AppKids.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Added_ArrayInts_with_WordId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_ArrayInts_with_WordId));
        
        string IMigrationMetadata.Id
        {
            get { return "201409251500191_Added_ArrayInts_with_WordId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
