// <auto-generated />
namespace Uni_AppKids.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class NewAttributesToWordModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewAttributesToWordModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201411280728032_NewAttributesToWordModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
