// <auto-generated />
namespace Uni_AppKids.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_UsernName_To_PhraseDictionary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_UsernName_To_PhraseDictionary));
        
        string IMigrationMetadata.Id
        {
            get { return "201409251512579_Add_UsernName_To_PhraseDictionary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
